package security

import "strings"

var routePermissionRegistry = map[string]string{
	"GET /config":                                          PermissionSystemConfigSettingsRead,
	"GET /config/tools":                                    PermissionSystemConfigSettingsRead,
	"PUT /config":                                          PermissionSystemConfigSettingsUpdate,
	"POST /config/apply":                                   PermissionSystemRuntimeConfigApply,
	"POST /config/test-openai":                             PermissionSystemModelConnectivityTest,
	"GET /security/web-users":                              PermissionSystemWebUserRead,
	"POST /security/web-users":                             PermissionSystemWebUserCreate,
	"PUT /security/web-users/:id":                          PermissionSystemWebUserUpdate,
	"POST /security/web-users/:id/reset-password":          PermissionSystemWebUserCredentialReset,
	"DELETE /security/web-users/:id":                       PermissionSystemWebUserDelete,
	"GET /security/web-access-roles":                       PermissionSystemWebAccessRoleRead,
	"POST /security/web-access-roles":                      PermissionSystemWebAccessRoleCreate,
	"PUT /security/web-access-roles/:id":                   PermissionSystemWebAccessRoleUpdate,
	"DELETE /security/web-access-roles/:id":                PermissionSystemWebAccessRoleDelete,
	"GET /security/web-access-roles/permission-catalog":    PermissionSystemWebAccessRoleRead,
	"POST /robot/test":                                     PermissionAgentRobotTestExecute,
	"POST /agent-loop":                                     PermissionAgentRunExecute,
	"POST /agent-loop/stream":                              PermissionAgentRunExecute,
	"POST /agent-loop/cancel":                              PermissionAgentRunStop,
	"GET /agent-loop/tasks":                                PermissionAgentRunRead,
	"GET /agent-loop/tasks/completed":                      PermissionAgentRunRead,
	"POST /multi-agent":                                    PermissionAgentMultiRunExecute,
	"POST /multi-agent/stream":                             PermissionAgentMultiRunExecute,
	"GET /multi-agent/markdown-agents":                     PermissionAgentMarkdownAgentRead,
	"GET /multi-agent/markdown-agents/:filename":           PermissionAgentMarkdownAgentRead,
	"POST /multi-agent/markdown-agents":                    PermissionAgentMarkdownAgentCreate,
	"PUT /multi-agent/markdown-agents/:filename":           PermissionAgentMarkdownAgentUpdate,
	"DELETE /multi-agent/markdown-agents/:filename":        PermissionAgentMarkdownAgentDelete,
	"POST /fofa/search":                                    PermissionIntelFofaQueryExecute,
	"POST /fofa/parse":                                     PermissionIntelFofaQueryExecute,
	"POST /batch-tasks":                                    PermissionTaskBatchQueueCreate,
	"GET /batch-tasks":                                     PermissionTaskBatchQueueRead,
	"GET /batch-tasks/:queueId":                            PermissionTaskBatchQueueRead,
	"POST /batch-tasks/:queueId/start":                     PermissionTaskBatchQueueStart,
	"POST /batch-tasks/:queueId/pause":                     PermissionTaskBatchQueueStop,
	"PUT /batch-tasks/:queueId/schedule-enabled":           PermissionTaskBatchQueueUpdate,
	"DELETE /batch-tasks/:queueId":                         PermissionTaskBatchQueueDelete,
	"PUT /batch-tasks/:queueId/tasks/:taskId":              PermissionTaskBatchTaskUpdate,
	"POST /batch-tasks/:queueId/tasks":                     PermissionTaskBatchTaskCreate,
	"DELETE /batch-tasks/:queueId/tasks/:taskId":           PermissionTaskBatchTaskDelete,
	"POST /conversations":                                  PermissionTaskConversationCreate,
	"GET /conversations":                                   PermissionTaskConversationRead,
	"GET /conversations/:id":                               PermissionTaskConversationRead,
	"GET /messages/:id/process-details":                    PermissionTaskConversationRead,
	"PUT /conversations/:id":                               PermissionTaskConversationUpdate,
	"DELETE /conversations/:id":                            PermissionTaskConversationDelete,
	"POST /conversations/:id/delete-turn":                  PermissionTaskConversationUpdate,
	"PUT /conversations/:id/pinned":                        PermissionTaskConversationUpdate,
	"POST /groups":                                         PermissionTaskGroupCreate,
	"GET /groups":                                          PermissionTaskGroupRead,
	"GET /groups/:id":                                      PermissionTaskGroupRead,
	"PUT /groups/:id":                                      PermissionTaskGroupUpdate,
	"DELETE /groups/:id":                                   PermissionTaskGroupDelete,
	"PUT /groups/:id/pinned":                               PermissionTaskGroupUpdate,
	"GET /groups/:id/conversations":                        PermissionTaskGroupRead,
	"GET /groups/mappings":                                 PermissionTaskGroupRead,
	"POST /groups/conversations":                           PermissionTaskGroupUpdate,
	"DELETE /groups/:id/conversations/:conversationId":     PermissionTaskGroupUpdate,
	"PUT /groups/:id/conversations/:conversationId/pinned": PermissionTaskGroupUpdate,
	"GET /monitor":                                         PermissionTaskExecutionRead,
	"GET /monitor/execution/:id":                           PermissionTaskExecutionRead,
	"POST /monitor/executions/names":                       PermissionTaskExecutionRead,
	"DELETE /monitor/execution/:id":                        PermissionTaskExecutionDelete,
	"DELETE /monitor/executions":                           PermissionTaskExecutionDelete,
	"GET /monitor/stats":                                   PermissionTaskExecutionRead,
	"GET /attack-chain/:conversationId":                    PermissionTaskAttackChainRead,
	"POST /attack-chain/:conversationId/regenerate":        PermissionTaskAttackChainRegenerate,
	"GET /conversations/:id/results":                       PermissionTaskConversationResultRead,
}

func LookupRoutePermission(method, path string) (string, bool) {
	key := strings.ToUpper(strings.TrimSpace(method)) + " " + strings.TrimSpace(path)
	permission, ok := routePermissionRegistry[key]
	return permission, ok
}
